<a href="https://colab.research.google.com/github/bhoomika6214/MyTutorial/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array=np.array([2,3,4])
print(array)
np.shape(array)
np.size(array)

[2 3 4]


3

In [ ]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=2
b=3
print("Addition "+str(a+b))
print("Subtration "+str(a-b))
print("Multiplication "+str(a*b))
print("Division "+str(a/b))
print("Modulus "+str(a%b))

Addition 5
Subtration -1
Multiplication 6
Division 0.6666666666666666
Modulus 2


In [ ]:
array2=np.array([2,3,4,5])
array3=np.array([5,8,3,2])
print(array2+array3)
print(array2-array3)
print(array2*array3)

[ 7 11  7  7]
[-3 -5  1  3]
[10 24 12 10]


In [ ]:
array4=[67,50,90,33,23,45,12,60,50,33,61]
x=np.mean(array4)
y=np.median(array4)
print(x)
print(y)

47.63636363636363
50.0


In [ ]:
from scipy import stats
speed = [99,86,13,44,56,90,90]
z=stats.mode(speed)
print(z)

ModeResult(mode=np.int64(90), count=np.int64(2))


In [ ]:
X=[[1,2,3],
   [3,5,6],
    [3,7,8]]

Y=[[1,2,3],
   [3,5,6],
    [3,7,8]]

result=[[0,0,0],
   [0,0,0],
    [0,0,0]]

for i in range(len(X)):
  for j in range(len(X[0])):
    result[i][j]=X[i][j]+Y[i][j]

for r in result:
  print(r)

[2, 4, 6]
[6, 10, 12]
[6, 14, 16]
